### ISSUE TITLE
toNewickApp not working?

### ISSUE THREAD

**Issue by Wytamma** [clockor2/phylojs#67]
The toNewickApp (https://clockor2.github.io/phylojs/examples/toNewickApp/) in the docs doesn't seem to be working.

This is the console error
```
TypeError: Cannot read properties of undefined (reading 'root')
    at Module.i (newick.ts:9:14)
    at reader.onload (pen.js:16:57)
```

**Comment by LeoFeatherstone** [comment]
Can you link me to the tree you were testing with?

**Comment by Wytamma** [comment]
I just used the example nexus tree on the page
